In [9]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [7]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

transposed_arr = arr.T
print("Transposed Array:\n", transposed_arr)


Original Array:
 [[ 53  68 100]
 [ 73  88  53]
 [ 75  79  81]]
Transposed Array:
 [[ 53  73  75]
 [ 68  88  79]
 [100  53  81]]


In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array. 

In [11]:
# 1D array with 10 elements
arr = np.arange(10)
print("1D Array:\n", arr)
# Reshape to 2x5
arr_2x5 = arr.reshape(2, 5)
print("2x5 Array:\n", arr_2x5)
# Reshape to 5x2
arr_5x2 = arr.reshape(5, 2)
print("5x2 Array:\n", arr_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array. 

In [13]:
#4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr)

#border of zeros to make it 6x6
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Array with Zero Border:\n", arr_with_border)


Original 4x4 Array:
 [[0.23646397 0.36189872 0.97275698 0.37964314]
 [0.76304367 0.00560399 0.28637706 0.20232406]
 [0.41162063 0.38106678 0.80968554 0.03918393]
 [0.06931493 0.70687138 0.31413639 0.45937644]]
Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.23646397 0.36189872 0.97275698 0.37964314 0.        ]
 [0.         0.76304367 0.00560399 0.28637706 0.20232406 0.        ]
 [0.         0.41162063 0.38106678 0.80968554 0.03918393 0.        ]
 [0.         0.06931493 0.70687138 0.31413639 0.45937644 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [15]:
arr = np.arange(10, 61, 5)
print("Array from 10 to 60 with step 5:\n", arr)


Array from 10 to 60 with step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [17]:
arr = np.array(['python', 'numpy', 'pandas'])

#different case transformations
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)

print("Uppercase:\n", uppercase)
print("Lowercase:\n", lowercase)
print("Titlecase:\n", titlecase)


Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Titlecase:
 ['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [19]:
#array of words
arr = np.array(['hello', 'world', 'numpy'])
# Insert a space between each character
spaced_words = np.char.join(' ', arr)
print("Words with spaces:\n", spaced_words)


Words with spaces:
 ['h e l l o' 'w o r l d' 'n u m p y']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [21]:
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# Element-wise operations
add = np.add(arr1, arr2)
subtract = np.subtract(arr1, arr2)
multiply = np.multiply(arr1, arr2)
divide = np.divide(arr1, arr2)

print("Addition:\n", add)
print("Subtraction:\n", subtract)
print("Multiplication:\n", multiply)
print("Division:\n", divide)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements. 

In [23]:
# 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array. 

In [25]:
arr = np.random.randint(0, 1001, 100)
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Filter prime numbers
primes = arr[np.vectorize(is_prime)(arr)]
print("Prime Numbers:\n", primes)


Prime Numbers:
 [103 227 163 191 541 607 719 653 541 691  53 167 131 313 739 347 449]


In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [27]:
temperatures = np.random.randint(20, 35, 30)
print("Daily Temperatures:\n", temperatures)

# Reshape into weeks (4 weeks of 7 days, plus 2 extra days)
weekly_temps = np.array_split(temperatures, 5)  # Handles the remaining days in the last week

# Calculate weekly averages
weekly_averages = [week.mean() for week in weekly_temps]
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [25 23 32 25 26 23 34 26 25 27 25 21 34 20 31 22 31 25 28 22 23 30 30 30
 30 32 22 20 32 32]
Weekly Averages:
 [25.666666666666668, 26.333333333333332, 27.166666666666668, 27.166666666666668, 28.0]
